// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzflemwkgzrbzvfvitvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZmxlbXdrZ3pyYnp2ZnZpdHZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTMzNjksImV4cCI6MjA2NzQ2OTM2OX0.lGlo6tUX08xPlvotvHigWkqq5zqSSP0Y9pkY9lSWh8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});